### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by tony-li-avepoint** [gxrsprite/eflayMapHack#1]
How to contact you?

**Comment by gxrsprite** [comment]
This MH have no update.    What you want to know ?

**Comment by tony-li-avepoint** [comment]
how to support 1.27?

**Comment by gxrsprite** [comment]
Learn how it work on 1.26, Compare  maphack  ON and OFF what changed in war3 main dll by ollydbg. You can find 1.26 address 
in MH code.  Then find similar assembly code on 1.27 and re-code it same way. Search jass function name can help you get new memory address. This requires proficiency.  I don't even know more.

**Comment by tony-li-avepoint** [comment]
Thanks for your reply, that's enough, have a good day!
